services:
  webpack:
    # Runs the webpack server for local development.
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - map-node-modules:/app/node_modules
    command: npm run serve

  app:
    image: map
    container_name: map
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - map-node-modules:/app/node_modules
    environment:
      DJANGO_SECRET_KEY: reallysupersecret
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_DEBUG: "True"
      PGPASSWORD: postgres
    entrypoint: /app/docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: map-postgres
    image: postgis/postgis
    # postgis/postgis:latest does not publish an ARM64 image, so we force
    # AMD64 emulation to support Apple Silicon (M1/M2/M3) Macs
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: map
    volumes:
      - map-db-data:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  map-db-data:
  map-node-modules:
